name: helium
services:
  helium:
    image: disk91/console
    restart: unless-stopped
    volumes:
      - ./dev/helium/testnet.bin:/etc/helium/pkey.bin
      - ./dev/helium/configuration.properties:/configuration.properties
    depends_on:
      - postgres
      - mongo
      - mosquitto
      - redis
      - chirpstack
    ports:
      - 127.0.0.1:8081:8081

  chirpstack:
    image: chirpstack/chirpstack:4.14.1
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./dev/chirpstack:/etc/chirpstack
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8070:8070

#  chirpstack-rest-api:
#    image: chirpstack/chirpstack-rest-api:4.14.1
#    restart: unless-stopped
#    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
#    ports:
#      - 127.0.0.1:8090:8090
#    depends_on:
#      - chirpstack
#    logging: *logs

  postgres:
    image: postgres:14-alpine
    shm_size: 512m
    restart: unless-stopped
    command: postgres -c 'max_connections=250'
    volumes:
      - ./dev/postgresql/initdb:/docker-entrypoint-initdb.d
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis:/data

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 127.0.0.1:1883:1883
    volumes:
      - ./chirpstack/configuration/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto:/mosquitto/data

volumes:
  psql:
  mongo:
  mosquitto:
  redis: